### ISSUE TITLE
App structure does not match the description

### ISSUE THREAD

**Issue by Markusxmr** [Vheissu/aurelia-starter-node#1]
Greetings,

The description mentions that there is client and server folder, but the app structure is kinda...different. Am I missing something?

**Comment by Vheissu** [comment]
@Markusxmr 

I changed the structure after experiencing issues, however, I have since got that stuff to work. So the latest repository uses the client and server folder structure as per the README. Sorry for the confusion.

**Comment by Markusxmr** [comment]
Cool. No prob. Thank you
